import type { Metadata } from "next";
import "./globals.css";
import Footer from "../../components/Footer";
import SideIconBar from "../../components/SideIconBar";
import Nav from "../../components/Nav";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Poornima College Alumni Society",
  description: "Generated by PCAS TEAM",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon_io/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon_io/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon_io/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon_io/favicon-16x16.png" />
        <link rel="manifest" href="/favicon_io/manifest.json" />
      </head>
      <body className="body">
        <div className="flex w-screen flex-col justify-center items-center">
          <div className="w-full md:ml-16 md:mr-16 xs:ml-8 xs:mr-8">
            <Nav />
          </div>
          <SideIconBar />
          {children}
          <div className="w-full flex justify-center md:ml-16 md:mr-16 xs:ml-8 xs:mr-8">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
